favicon: /assets/images/favicon.svg
logo: /assets/images/Nikan.jpg

show_info: true
show_contacts: true

main_language_code: en
fullname: Nikan Mehrara
#age: 25 y.o.
location: Farmington Hills, MI
language: English, Azerbaijani
bt_mailto: <a href="mailto:nmehrara@ltu.edu">Send me <strong>Mail</strong></a>
bt_github: <a href="https://github.com/nikemehr">Profile <strong>GitHub</strong></a>
#bt_pdf: <a href="https://raw.githubusercontent.com/Annndruha/annndruha.github.io/main/assets/pdf/marakulin_en.pdf">Download <strong>CV PDF</strong></a>

second_language_code: az
second_fullname: Nikan Mehrara
#second_age: 25 лет
second_location: Farmington Hills, MI
second_language: English, Azerbaijani
second_bt_mailto: <a href="mailto:nmehrara@ltu.edu">Написать на <strong>Почту</strong></a>
second_bt_github: <a href="https://github.com/nikemehr">Профиль <strong>GitHub</strong></a>
second_bt_pdf: <a href="https://raw.githubusercontent.com/Annndruha/annndruha.github.io/main/assets/pdf/marakulin_ru.pdf">Скачать резюме<strong>PDF</strong></a>

show_branding: True
branding_link: https://annndruha.space
branding_link_text: annndruha.space
branding_favicon: https://annndruha.space/icons/favicon.svg

remote_theme: annndruha/minimal-resume@v2.1.0
plugins:
- jekyll-remote-theme
